name: Continuous Deployment
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

env:
  NODE_VERSION: 16.13.1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Run Tests
        run: yarn test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Lint Code
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    needs:
      - test
      - lint
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Build Application
        run: yarn build
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/swissmanu/xmas-tree-demo:${{ github.sha }}
      - name: Show Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build
    environment:
      name: Azure
      url: https://xmas-tree-demo.azurewebsites.net/
    steps:
      - uses: azure/webapps-deploy@v2
        with:
          app-name: "xmas-tree-demo"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: "ghcr.io/swissmanu/xmas-tree-demo:${{ github.sha }}"
